
# search radius for players, ItemFinder.find.admin removes the max_search_radius for admins. 
# There is still a builtin max radius of 1000 to prevent clumsy admins from crashing the server :)
default_search_radius: 20
max_search_radius: 50

# time chests stay marked in ticks
marker_timeout: 500

# If enabled, the plugin will also search shulkerboxes inside chests. 
search_shulkerbox_recursively: true

messages:
  error:
    unknown_material: "Material %s does not exist."
    must_be_ingame: "You must be ingame to use this command"
    must_hold_item: "Please hold the item you want to search for"
  info:
    search: "§6Searching for §a%s§6 in a radius of §a%d§6 blocks.§r"
    found:
      total: "§6Found §a%d§6 items in total:§r"
      container: "§6Chests: §a%d§r"
      floor: "§6Floor: §a%d§r"
      player: "§6Inventory: §a%d§r"
      ender: "§6EnderChest: §a%d§r"
      nothingFound: "§a%s§6 could not be found.§r"
