name: ItemFinder
main: me.lennartVH01.itemfinder.ItemFinder
version: 1.0.1-pre1
description: Simple container searching plugin
author: lennartVH01
softdepend: [Worldguard, Towny]

commands:
  find:
    description: Search nearby chests
    permission: ItemFinder.find
    usage: "Usage: /<command> [material[:data]] [range]"

permissions:
  ItemFinder.find:
    description: "Gives access to /find"
    default: true
  
  ItemFinder.*:
    description: "Gives access to all features of /find"
    default: op
    children:
      ItemFinder.find: true
      ItemFinder.in.*: true
      ItemFinder.longRange: true
      ItemFinder.ignorePerms: true
  
  ItemFinder.in.*:
    description: "Allows searching all available inventories"
    default: true
    children:
      ItemFinder.in.container: true
      ItemFinder.in.floor: true
      ItemFinder.in.inventory: true
      ItemFinder.in.enderchest: true
  
  ItemFinder.longRange:
    description: "Removes range limitation on /find"
    default: op
  ItemFinder.ignorePerms:
    description: "Overrides permission check with other plugins for searching inventories"
    default: op
  
  ItemFinder.in.container:
    description: "Allows to find items in containers"
    default: true
  ItemFinder.in.floor:
    description: "Allows to find items on the floor"
    default: true
  ItemFinder.in.inventory:
    description: "Allows to find items in their inventory"
    default: true
  ItemFinder.in.enderchest:
    description: "Allows to find items in their enderchest"
    default: true
