name: ItemFinder
main: me.lennartVH01.itemfinder.ItemFinder
version: 1.0-alpha.3
description: Simple container searching plugin
author: lennartVH01
softdepend: [Worldguard, Towny]

commands:
  find:
    description: Search nearby chests
    permission: ItemFinder.find
    usage: "Usage: /<command> [material[:data]] [range]"

permissions:
  ItemFinder.find:
    description: "Gives access to /find"
    default: true
  
  ItemFinder.find.*:
    description: "Gives access to all admin features of /find"
    default: op
    children:
      ItemFinder.find.longRange: true
      ItemFinder.find.ignorePerms: true
  ItemFinder.find.longRange:
    description: "Removes range limitation on /find"
    default: op
  ItemFinder.find.ignorePerms:
    description: "Overrides permission check with other plugins for searching inventories"
    default: op